server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: textai-backend
  
  # 데이터베이스 설정 (필요시)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 로깅 설정
logging:
  level:
    com.textai: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# AI 서비스 설정 (예시)
textai:
  openai:
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    model: gpt-3.5-turbo
  google:
    translate-api-key: ${GOOGLE_TRANSLATE_API_KEY:your-api-key-here}
