version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./react-version
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    networks:
      - textai-network

  # Spring Boot Backend
  backend:
    build:
      context: ./spring-boot-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
    networks:
      - textai-network

  # Database (optional)
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=textai
      - POSTGRES_USER=textai
      - POSTGRES_PASSWORD=textai123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - textai-network

networks:
  textai-network:
    driver: bridge

volumes:
  postgres_data:
